-- 用户中心模块（标准 SQL 版）
USE xhxt_db;

-- 如果你不想重装数据库，请执行以下语句补齐字段
-- ALTER TABLE users ADD COLUMN real_name VARCHAR(64) DEFAULT NULL COMMENT '真实姓名';
-- ALTER TABLE users ADD COLUMN phone VARCHAR(32) DEFAULT NULL COMMENT '手机号';
-- ALTER TABLE users ADD COLUMN email VARCHAR(128) DEFAULT NULL COMMENT '邮箱';
-- ALTER TABLE users ADD COLUMN gender TINYINT DEFAULT 0 COMMENT '性别:0未知 1男 2女';
-- ALTER TABLE users ADD COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

CREATE TABLE IF NOT EXISTS user_address (
  id             BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  user_id        BIGINT NOT NULL COMMENT '用户ID',
  receiver_name  VARCHAR(64) NOT NULL COMMENT '收货人',
  receiver_phone VARCHAR(32) NOT NULL COMMENT '联系电话',
  province       VARCHAR(64) DEFAULT NULL COMMENT '省',
  city           VARCHAR(64) DEFAULT NULL COMMENT '市',
  district       VARCHAR(64) DEFAULT NULL COMMENT '区',
  detail_address VARCHAR(255) NOT NULL COMMENT '详细地址',
  is_default     TINYINT NOT NULL DEFAULT 0 COMMENT '是否默认地址:1是0否',
  create_time    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  KEY idx_address_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户收货地址';
