-- 内容管理模块：轮播图、公告、新闻资讯
SET NAMES utf8mb4;
USE xhxt_db;

-- 1. 轮播图
CREATE TABLE IF NOT EXISTS banner (
  id          BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  title       VARCHAR(100) DEFAULT NULL COMMENT '标题',
  img_url     VARCHAR(255) NOT NULL COMMENT '图片地址',
  link_url    VARCHAR(255) DEFAULT NULL COMMENT '跳转链接',
  sort_no     INT DEFAULT 0 COMMENT '排序',
  status      TINYINT DEFAULT 1 COMMENT '1启用 0禁用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='首页轮播图';

-- 2. 公告
CREATE TABLE IF NOT EXISTS notice (
  id          BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  title       VARCHAR(200) NOT NULL COMMENT '公告标题',
  content     TEXT NOT NULL COMMENT '公告内容',
  status      TINYINT DEFAULT 1 COMMENT '1发布 0撤回',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统公告';

-- 3. 资讯分类
CREATE TABLE IF NOT EXISTS news_category (
  id            BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  category_name VARCHAR(64) NOT NULL COMMENT '分类名称',
  sort_no       INT DEFAULT 0 COMMENT '排序',
  create_time   DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资讯分类';

-- 4. 新闻资讯内容
CREATE TABLE IF NOT EXISTS news_info (
  id            BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  category_id   BIGINT NOT NULL COMMENT '分类ID',
  title         VARCHAR(200) NOT NULL COMMENT '资讯标题',
  summary       VARCHAR(500) DEFAULT NULL COMMENT '简介',
  content       LONGTEXT NOT NULL COMMENT '正文内容',
  cover_img     VARCHAR(255) DEFAULT NULL COMMENT '封面图',
  view_count    INT DEFAULT 0 COMMENT '浏览量',
  status        TINYINT DEFAULT 1 COMMENT '1发布 0下线',
  create_time   DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_news_category (category_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='新闻资讯';